### ISSUE TITLE
require.async 多行（有换行符）时，解析不出来

### ISSUE THREAD

**Issue by Alex1990** [seajs/crequire#2]
运行以下代码：

``` js
var str = 'require.async("slider", function(){\nalert("loaded");\n});';
var parseDependencies = require('searequire');

console.dir(parseDependencies(str, true));
```

结果为： `[]`

**Comment by Alex1990** [comment]
顺便问一个问题：增加解析压缩后的文件好不好呢？（性能损失大？）
如， 使用正则提取出 `'define(function(a,b,c){'` 里的 `a`，作为 `require`。

**Comment by army8735** [comment]
不是多行，是不支持require.async(String, Function)。

``` js
require.async(String)
```

只匹配了这种模式。

**Comment by army8735** [comment]
require(String, Function)同样没匹配。加上是否有问题想想……

**Comment by army8735** [comment]
压缩后的很难的。就算你认为a是require的压缩名，但会有局部变量也叫a但不是require的。这种情况极难区分。

**Comment by Alex1990** [comment]
使用 uglify 压缩，它会自动处理变量名的，局部变量有a ，它会用其他的单个字母表示的。

**Comment by army8735** [comment]
``` js
define(function(a) {
  ~function() {
    var a = 1;
  }
})
```

局部变量覆盖全局

**Comment by Alex1990** [comment]
``` js
define(function(require) {
  function foo() {
    var alert = require('alert');
    var a = 1;
    alert(a);
  }

  foo();
});
```

http://skalman.github.io/UglifyJS-online/ 压缩后：

``` js
define(function(n){function e(){var e=n("alert"),f=1;e(f)}e()});
```

可能这个功能没什么用

**Comment by army8735** [comment]
要看压缩算法的策略。

有可能局部变量里声明了个require，然后压缩成和关键字一样。又或者在一个context下没有使用require，那么将其它变量压缩为和关键字一样，这样压缩是为了gzip节省字符，而且运行完全正常语法语义正确。
