### ISSUE TITLE
require.async匹配情况未考虑完整

### ISSUE THREAD

**Issue by nuintun** [seajs/crequire#4]
对于`async`路径是表达式的情况排除不考虑，下面：

``` js
require.async(['start', 'stop']);
require.async(['start', 'stop'], function (start, stop){});
```

这种情况没有匹配到。

**Comment by army8735** [comment]
async居然还要支持数组……

**Comment by nuintun** [comment]
sea的async是支持数组的，只不过出场几率比较小点而已, Orz, 这个是对提取来说的确很坑！

**Comment by nuintun** [comment]
还有

``` js
crequire(code, function(node) {
  // 这里要返回整个字符串才能替换，更好的做法是继续返回 node，
  // 更改node的path可以直接反映到结果，这样node的string属性就可以去掉了
  return 'require("id")';
})
```

**Comment by army8735** [comment]
那是为了保持兼容

**Comment by army8735** [comment]
async又要考虑进来又不是用require的目的是什么？

**Comment by nuintun** [comment]
额，这里是蛮纠结。
主要是在`async`引用了`alias`，想在`transport`的时候替换`alias`，这时候抓这些`async`就有用了~~

**Comment by army8735** [comment]
require也有经过这个分析

**Comment by nuintun** [comment]
@army8735 用 `crequre` 和 `detective` 组合了个，速度介于两者之间，不过不会误伤了~

`crequre` 在

``` js
require.async(document.domain + '/root' + file);
```

的情况下会把 `/root` 提取出来，在替换的时候误伤 - -!

https://github.com/Nuintun/umd-deps

**Comment by army8735** [comment]
会提出root？

**Comment by popomore** [comment]
变量的情况下提出来也没用吧，因为是运行时动态生成的。

**Comment by army8735** [comment]
他说的是可以提出来，这明明是忽略掉的。
