### ISSUE TITLE
静态字符串拼接无法识别

### ISSUE THREAD

**Issue by jaredleechn** [seajs/crequire#5]
@army8735 老师，测试了下，没办法识别以下两种情况：

``` javascript
var q = require('jquer' + 'y');

var r = require('jquer' +
                        'y');
```

**Comment by army8735** [comment]
不支持动态拼接解析

**Comment by jaredleechn** [comment]
webpack 和 nodejs 都能够识别静态字符串拼接的， @army8735  老师要不要考虑支持一下

**Comment by army8735** [comment]
nodejs是真的运行时的支持；webpack是假的支持，极简单的同一上下文加运算。

这个要加进来相当复杂，体积也暴增。es6的module规范也是静态解析不支持动态，所以我是加不来了。
